### PR TITLE
fix: allow all combinations of `describe`, `it` and `test` to `skip` modifier

### PR DESCRIPTION
**Pull request by wellwelwel**
Fixes: https://github.com/wellwelwel/poku/commit/b756605142ec2a1a22d5fe46d2f62aade2812d51#r146279295

### CODE REVIEW

**Comment by mrazauskas** [comment]
Nice! Isn't it that `.todo` has similar issue?

**Comment by wellwelwel** [comment]
Thanks, @mrazauskas.

> Isn't it that `.todo` has similar issue?

I don't know if that will make sense in English, but a "to-do" without a "do" seems to be just an alternative name for the `skip` method.

My idea/approach for each one is:

### .skip

- A debugging helper
- Message is optional
- Callback is required

### .todo

- A planning helper for incomplete or further tests
- Message is required
- Callback is optional

**Comment by mrazauskas** [comment]
That's right. It is just a skipped test, but semantically it is not skipped, but simply not yet (properly) implemented.

**Comment by mrazauskas** [comment]
Also if Poku allows tests without messages, I think the planning helper must allow those too. Why not?

**Comment by wellwelwel** [comment]
> Poku allows tests without messages

I think I get your point now. My problem with planning without a message is that it would cease to be a plan, for example:

- This is a `to-do`:

```ts
test.todo("Understand why the loop doesn't finish", () => {
  let i = 0;
  
  while (i >= 0) {
    i++;
  }
);
```

Same test, but this one wouldn't be a plan, just an ignored test:

```ts
test.skip(() => {
  let i = 0;
  
  while (i >= 0) {
    i++;
  }
);
```

Both will do exactly the same thing in practice (skip the tests), but one shows that there is planning behind the "improperly implemented" test, the other just ignores it. The real difference is in the final logs.

That said, I'd have no problem making `.todo` an alias for skip, but I would see it as a `feat` rather than a `fix`. If I understand right, the idea is that any test should be able to use a modifier without requiring any change to it.

**Comment by mrazauskas** [comment]
Looking at your example I think: why `.todo` is needed at all? Use `.skip` instead. Optional callback is not really so much useful, one can use a comment too:

```js
// TODO Why this loop does not work?
test.skip(() => {
  let i = 0;
  while (i >= 0) i++;
);
```

---

What if someone is building up a test without a message (since that is allowed):

```js
test.todo(() => {
  someCall();

  // assert this and that

  // TODO does not work yet, have to figure it out
  someOtherCall();

  // assert this and that
);
```

Here `.todo` can be replace with `.skip`, but semantics are different.

**Pull request merged**
